// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: altimeter.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_altimeter_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_altimeter_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3010000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3010001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "time.pb.h"
#pragma GCC system_header
#include <boost/shared_ptr.hpp>
#include <gazebo/util/system.hh>
#include "gazebo/msgs/MsgFactory.hh"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_altimeter_2eproto GZ_MSGS_VISIBLE
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct GZ_MSGS_VISIBLE TableStruct_altimeter_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern GZ_MSGS_VISIBLE const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_altimeter_2eproto;
namespace gazebo {
namespace msgs {
class Altimeter;
class AltimeterDefaultTypeInternal;
GZ_MSGS_VISIBLE extern AltimeterDefaultTypeInternal _Altimeter_default_instance_;
}  // namespace msgs
}  // namespace gazebo
PROTOBUF_NAMESPACE_OPEN
template<> GZ_MSGS_VISIBLE ::gazebo::msgs::Altimeter* Arena::CreateMaybeMessage<::gazebo::msgs::Altimeter>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace gazebo {
namespace msgs {

// ===================================================================

class GZ_MSGS_VISIBLE Altimeter :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:gazebo.msgs.Altimeter) */ {
 public:
  Altimeter();
  virtual ~Altimeter();

  Altimeter(const Altimeter& from);
  Altimeter(Altimeter&& from) noexcept
    : Altimeter() {
    *this = ::std::move(from);
  }

  inline Altimeter& operator=(const Altimeter& from) {
    CopyFrom(from);
    return *this;
  }
  inline Altimeter& operator=(Altimeter&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Altimeter& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Altimeter* internal_default_instance() {
    return reinterpret_cast<const Altimeter*>(
               &_Altimeter_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Altimeter& a, Altimeter& b) {
    a.Swap(&b);
  }
  inline void Swap(Altimeter* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Altimeter* New() const final {
    return CreateMaybeMessage<Altimeter>(nullptr);
  }

  Altimeter* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Altimeter>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Altimeter& from);
  void MergeFrom(const Altimeter& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Altimeter* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "gazebo.msgs.Altimeter";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_altimeter_2eproto);
    return ::descriptor_table_altimeter_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTimeFieldNumber = 1,
    kVerticalPositionFieldNumber = 2,
    kVerticalVelocityFieldNumber = 3,
    kVerticalReferenceFieldNumber = 4,
  };
  // required .gazebo.msgs.Time time = 1;
  bool has_time() const;
  private:
  bool _internal_has_time() const;
  public:
  void clear_time();
  const ::gazebo::msgs::Time& time() const;
  ::gazebo::msgs::Time* release_time();
  ::gazebo::msgs::Time* mutable_time();
  void set_allocated_time(::gazebo::msgs::Time* time);
  private:
  const ::gazebo::msgs::Time& _internal_time() const;
  ::gazebo::msgs::Time* _internal_mutable_time();
  public:

  // required double vertical_position = 2;
  bool has_vertical_position() const;
  private:
  bool _internal_has_vertical_position() const;
  public:
  void clear_vertical_position();
  double vertical_position() const;
  void set_vertical_position(double value);
  private:
  double _internal_vertical_position() const;
  void _internal_set_vertical_position(double value);
  public:

  // required double vertical_velocity = 3;
  bool has_vertical_velocity() const;
  private:
  bool _internal_has_vertical_velocity() const;
  public:
  void clear_vertical_velocity();
  double vertical_velocity() const;
  void set_vertical_velocity(double value);
  private:
  double _internal_vertical_velocity() const;
  void _internal_set_vertical_velocity(double value);
  public:

  // required double vertical_reference = 4;
  bool has_vertical_reference() const;
  private:
  bool _internal_has_vertical_reference() const;
  public:
  void clear_vertical_reference();
  double vertical_reference() const;
  void set_vertical_reference(double value);
  private:
  double _internal_vertical_reference() const;
  void _internal_set_vertical_reference(double value);
  public:

  // @@protoc_insertion_point(class_scope:gazebo.msgs.Altimeter)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::gazebo::msgs::Time* time_;
  double vertical_position_;
  double vertical_velocity_;
  double vertical_reference_;
  friend struct ::TableStruct_altimeter_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Altimeter

// required .gazebo.msgs.Time time = 1;
inline bool Altimeter::_internal_has_time() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || time_ != nullptr);
  return value;
}
inline bool Altimeter::has_time() const {
  return _internal_has_time();
}
inline const ::gazebo::msgs::Time& Altimeter::_internal_time() const {
  const ::gazebo::msgs::Time* p = time_;
  return p != nullptr ? *p : *reinterpret_cast<const ::gazebo::msgs::Time*>(
      &::gazebo::msgs::_Time_default_instance_);
}
inline const ::gazebo::msgs::Time& Altimeter::time() const {
  // @@protoc_insertion_point(field_get:gazebo.msgs.Altimeter.time)
  return _internal_time();
}
inline ::gazebo::msgs::Time* Altimeter::release_time() {
  // @@protoc_insertion_point(field_release:gazebo.msgs.Altimeter.time)
  _has_bits_[0] &= ~0x00000001u;
  ::gazebo::msgs::Time* temp = time_;
  time_ = nullptr;
  return temp;
}
inline ::gazebo::msgs::Time* Altimeter::_internal_mutable_time() {
  _has_bits_[0] |= 0x00000001u;
  if (time_ == nullptr) {
    auto* p = CreateMaybeMessage<::gazebo::msgs::Time>(GetArenaNoVirtual());
    time_ = p;
  }
  return time_;
}
inline ::gazebo::msgs::Time* Altimeter::mutable_time() {
  // @@protoc_insertion_point(field_mutable:gazebo.msgs.Altimeter.time)
  return _internal_mutable_time();
}
inline void Altimeter::set_allocated_time(::gazebo::msgs::Time* time) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(time_);
  }
  if (time) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      time = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, time, submessage_arena);
    }
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  time_ = time;
  // @@protoc_insertion_point(field_set_allocated:gazebo.msgs.Altimeter.time)
}

// required double vertical_position = 2;
inline bool Altimeter::_internal_has_vertical_position() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool Altimeter::has_vertical_position() const {
  return _internal_has_vertical_position();
}
inline void Altimeter::clear_vertical_position() {
  vertical_position_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline double Altimeter::_internal_vertical_position() const {
  return vertical_position_;
}
inline double Altimeter::vertical_position() const {
  // @@protoc_insertion_point(field_get:gazebo.msgs.Altimeter.vertical_position)
  return _internal_vertical_position();
}
inline void Altimeter::_internal_set_vertical_position(double value) {
  _has_bits_[0] |= 0x00000002u;
  vertical_position_ = value;
}
inline void Altimeter::set_vertical_position(double value) {
  _internal_set_vertical_position(value);
  // @@protoc_insertion_point(field_set:gazebo.msgs.Altimeter.vertical_position)
}

// required double vertical_velocity = 3;
inline bool Altimeter::_internal_has_vertical_velocity() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool Altimeter::has_vertical_velocity() const {
  return _internal_has_vertical_velocity();
}
inline void Altimeter::clear_vertical_velocity() {
  vertical_velocity_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline double Altimeter::_internal_vertical_velocity() const {
  return vertical_velocity_;
}
inline double Altimeter::vertical_velocity() const {
  // @@protoc_insertion_point(field_get:gazebo.msgs.Altimeter.vertical_velocity)
  return _internal_vertical_velocity();
}
inline void Altimeter::_internal_set_vertical_velocity(double value) {
  _has_bits_[0] |= 0x00000004u;
  vertical_velocity_ = value;
}
inline void Altimeter::set_vertical_velocity(double value) {
  _internal_set_vertical_velocity(value);
  // @@protoc_insertion_point(field_set:gazebo.msgs.Altimeter.vertical_velocity)
}

// required double vertical_reference = 4;
inline bool Altimeter::_internal_has_vertical_reference() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool Altimeter::has_vertical_reference() const {
  return _internal_has_vertical_reference();
}
inline void Altimeter::clear_vertical_reference() {
  vertical_reference_ = 0;
  _has_bits_[0] &= ~0x00000008u;
}
inline double Altimeter::_internal_vertical_reference() const {
  return vertical_reference_;
}
inline double Altimeter::vertical_reference() const {
  // @@protoc_insertion_point(field_get:gazebo.msgs.Altimeter.vertical_reference)
  return _internal_vertical_reference();
}
inline void Altimeter::_internal_set_vertical_reference(double value) {
  _has_bits_[0] |= 0x00000008u;
  vertical_reference_ = value;
}
inline void Altimeter::set_vertical_reference(double value) {
  _internal_set_vertical_reference(value);
  // @@protoc_insertion_point(field_set:gazebo.msgs.Altimeter.vertical_reference)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

typedef boost::shared_ptr<gazebo::msgs::Altimeter> AltimeterPtr;
// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace gazebo

typedef const boost::shared_ptr<gazebo::msgs::Altimeter const> ConstAltimeterPtr;
// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_altimeter_2eproto
