// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: logical_camera_sensor.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_logical_5fcamera_5fsensor_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_logical_5fcamera_5fsensor_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3010000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3010001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#pragma GCC system_header
#include <boost/shared_ptr.hpp>
#include <gazebo/util/system.hh>
#include "gazebo/msgs/MsgFactory.hh"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_logical_5fcamera_5fsensor_2eproto GZ_MSGS_VISIBLE
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct GZ_MSGS_VISIBLE TableStruct_logical_5fcamera_5fsensor_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern GZ_MSGS_VISIBLE const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_logical_5fcamera_5fsensor_2eproto;
namespace gazebo {
namespace msgs {
class LogicalCameraSensor;
class LogicalCameraSensorDefaultTypeInternal;
GZ_MSGS_VISIBLE extern LogicalCameraSensorDefaultTypeInternal _LogicalCameraSensor_default_instance_;
}  // namespace msgs
}  // namespace gazebo
PROTOBUF_NAMESPACE_OPEN
template<> GZ_MSGS_VISIBLE ::gazebo::msgs::LogicalCameraSensor* Arena::CreateMaybeMessage<::gazebo::msgs::LogicalCameraSensor>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace gazebo {
namespace msgs {

// ===================================================================

class GZ_MSGS_VISIBLE LogicalCameraSensor :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:gazebo.msgs.LogicalCameraSensor) */ {
 public:
  LogicalCameraSensor();
  virtual ~LogicalCameraSensor();

  LogicalCameraSensor(const LogicalCameraSensor& from);
  LogicalCameraSensor(LogicalCameraSensor&& from) noexcept
    : LogicalCameraSensor() {
    *this = ::std::move(from);
  }

  inline LogicalCameraSensor& operator=(const LogicalCameraSensor& from) {
    CopyFrom(from);
    return *this;
  }
  inline LogicalCameraSensor& operator=(LogicalCameraSensor&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const LogicalCameraSensor& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LogicalCameraSensor* internal_default_instance() {
    return reinterpret_cast<const LogicalCameraSensor*>(
               &_LogicalCameraSensor_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(LogicalCameraSensor& a, LogicalCameraSensor& b) {
    a.Swap(&b);
  }
  inline void Swap(LogicalCameraSensor* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline LogicalCameraSensor* New() const final {
    return CreateMaybeMessage<LogicalCameraSensor>(nullptr);
  }

  LogicalCameraSensor* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<LogicalCameraSensor>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const LogicalCameraSensor& from);
  void MergeFrom(const LogicalCameraSensor& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LogicalCameraSensor* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "gazebo.msgs.LogicalCameraSensor";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_logical_5fcamera_5fsensor_2eproto);
    return ::descriptor_table_logical_5fcamera_5fsensor_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNearClipFieldNumber = 1,
    kFarClipFieldNumber = 2,
    kHorizontalFovFieldNumber = 3,
    kAspectRatioFieldNumber = 4,
  };
  // required double near_clip = 1;
  bool has_near_clip() const;
  private:
  bool _internal_has_near_clip() const;
  public:
  void clear_near_clip();
  double near_clip() const;
  void set_near_clip(double value);
  private:
  double _internal_near_clip() const;
  void _internal_set_near_clip(double value);
  public:

  // required double far_clip = 2;
  bool has_far_clip() const;
  private:
  bool _internal_has_far_clip() const;
  public:
  void clear_far_clip();
  double far_clip() const;
  void set_far_clip(double value);
  private:
  double _internal_far_clip() const;
  void _internal_set_far_clip(double value);
  public:

  // required double horizontal_fov = 3;
  bool has_horizontal_fov() const;
  private:
  bool _internal_has_horizontal_fov() const;
  public:
  void clear_horizontal_fov();
  double horizontal_fov() const;
  void set_horizontal_fov(double value);
  private:
  double _internal_horizontal_fov() const;
  void _internal_set_horizontal_fov(double value);
  public:

  // required double aspect_ratio = 4;
  bool has_aspect_ratio() const;
  private:
  bool _internal_has_aspect_ratio() const;
  public:
  void clear_aspect_ratio();
  double aspect_ratio() const;
  void set_aspect_ratio(double value);
  private:
  double _internal_aspect_ratio() const;
  void _internal_set_aspect_ratio(double value);
  public:

  // @@protoc_insertion_point(class_scope:gazebo.msgs.LogicalCameraSensor)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  double near_clip_;
  double far_clip_;
  double horizontal_fov_;
  double aspect_ratio_;
  friend struct ::TableStruct_logical_5fcamera_5fsensor_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// LogicalCameraSensor

// required double near_clip = 1;
inline bool LogicalCameraSensor::_internal_has_near_clip() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool LogicalCameraSensor::has_near_clip() const {
  return _internal_has_near_clip();
}
inline void LogicalCameraSensor::clear_near_clip() {
  near_clip_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline double LogicalCameraSensor::_internal_near_clip() const {
  return near_clip_;
}
inline double LogicalCameraSensor::near_clip() const {
  // @@protoc_insertion_point(field_get:gazebo.msgs.LogicalCameraSensor.near_clip)
  return _internal_near_clip();
}
inline void LogicalCameraSensor::_internal_set_near_clip(double value) {
  _has_bits_[0] |= 0x00000001u;
  near_clip_ = value;
}
inline void LogicalCameraSensor::set_near_clip(double value) {
  _internal_set_near_clip(value);
  // @@protoc_insertion_point(field_set:gazebo.msgs.LogicalCameraSensor.near_clip)
}

// required double far_clip = 2;
inline bool LogicalCameraSensor::_internal_has_far_clip() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool LogicalCameraSensor::has_far_clip() const {
  return _internal_has_far_clip();
}
inline void LogicalCameraSensor::clear_far_clip() {
  far_clip_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline double LogicalCameraSensor::_internal_far_clip() const {
  return far_clip_;
}
inline double LogicalCameraSensor::far_clip() const {
  // @@protoc_insertion_point(field_get:gazebo.msgs.LogicalCameraSensor.far_clip)
  return _internal_far_clip();
}
inline void LogicalCameraSensor::_internal_set_far_clip(double value) {
  _has_bits_[0] |= 0x00000002u;
  far_clip_ = value;
}
inline void LogicalCameraSensor::set_far_clip(double value) {
  _internal_set_far_clip(value);
  // @@protoc_insertion_point(field_set:gazebo.msgs.LogicalCameraSensor.far_clip)
}

// required double horizontal_fov = 3;
inline bool LogicalCameraSensor::_internal_has_horizontal_fov() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool LogicalCameraSensor::has_horizontal_fov() const {
  return _internal_has_horizontal_fov();
}
inline void LogicalCameraSensor::clear_horizontal_fov() {
  horizontal_fov_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline double LogicalCameraSensor::_internal_horizontal_fov() const {
  return horizontal_fov_;
}
inline double LogicalCameraSensor::horizontal_fov() const {
  // @@protoc_insertion_point(field_get:gazebo.msgs.LogicalCameraSensor.horizontal_fov)
  return _internal_horizontal_fov();
}
inline void LogicalCameraSensor::_internal_set_horizontal_fov(double value) {
  _has_bits_[0] |= 0x00000004u;
  horizontal_fov_ = value;
}
inline void LogicalCameraSensor::set_horizontal_fov(double value) {
  _internal_set_horizontal_fov(value);
  // @@protoc_insertion_point(field_set:gazebo.msgs.LogicalCameraSensor.horizontal_fov)
}

// required double aspect_ratio = 4;
inline bool LogicalCameraSensor::_internal_has_aspect_ratio() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool LogicalCameraSensor::has_aspect_ratio() const {
  return _internal_has_aspect_ratio();
}
inline void LogicalCameraSensor::clear_aspect_ratio() {
  aspect_ratio_ = 0;
  _has_bits_[0] &= ~0x00000008u;
}
inline double LogicalCameraSensor::_internal_aspect_ratio() const {
  return aspect_ratio_;
}
inline double LogicalCameraSensor::aspect_ratio() const {
  // @@protoc_insertion_point(field_get:gazebo.msgs.LogicalCameraSensor.aspect_ratio)
  return _internal_aspect_ratio();
}
inline void LogicalCameraSensor::_internal_set_aspect_ratio(double value) {
  _has_bits_[0] |= 0x00000008u;
  aspect_ratio_ = value;
}
inline void LogicalCameraSensor::set_aspect_ratio(double value) {
  _internal_set_aspect_ratio(value);
  // @@protoc_insertion_point(field_set:gazebo.msgs.LogicalCameraSensor.aspect_ratio)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

typedef boost::shared_ptr<gazebo::msgs::LogicalCameraSensor> LogicalCameraSensorPtr;
// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace gazebo

typedef const boost::shared_ptr<gazebo::msgs::LogicalCameraSensor const> ConstLogicalCameraSensorPtr;
// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_logical_5fcamera_5fsensor_2eproto
